apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-sonar-pv
  namespace: devops
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql-sonar   # adaptez selon votre environnement
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-sonar-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
